plugins {
    id 'java'
}

group 'org.mentalizr'
version = rootProject.file('version').text.trim()

repositories {
    mavenCentral()
    maven { url "https://raw.githubusercontent.com/arthurpicht/mvn-repo/main/releases"}
}

dependencies {
    implementation libs.ap.utils.core

    implementation libs.jakarta.xml.bind.api
    implementation libs.jersey.media.json.binding

    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.engine
}

test {
    useJUnitPlatform()
}
